import './globals.css'
import { Open_Sans } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { cn } from '@/lib/utils'

const font = Open_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Team Chat App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <ThemeProvider
          defaultTheme="dark"
          attribute="class"
          enableSystem={false}
          storageKey="theme"
        >
          <body className={cn(
            font.className,
            'bg-white dark:bg-[#313338]'
          )}>{children}</body>
        </ThemeProvider>
      </html>
    </ClerkProvider>
  )
}
